#!/bin/bash
set -e

echo "Pushed tag to main repo"
git push --tags

echo "Pushing changes into development"
git checkout development
git push origin development

echo "Pushing changes into master"
git checkout master
git push origin master

echo "Return to development branch"
git checkout development
